spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/psycontrol_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: psycontrol_user
    password:
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: none
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

config:
  file:
    upload-dir: /storage #For Docker container volume
    #upload-dir: ${HOME}/storage #For non root Linux filesystem
    #upload-dir: C:\\storage # For Windows filesystem
  jwt:
    secretKey: SuperSecreto
    validityInMilliseconds: 3600000 #60*60000 = 1Hour

logging:
  level:
    org:
      hibernate:
        #type:
        #descriptor:
        #sql:
        #BasicBinder: TRACE
        SQL: DEBUG
      springframework:
        security: DEBUG
