spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/psycontrol_db
    username: psycontrol_user
    password:
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: none
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

config:
  file:
    upload-dir: /storage #For Docker container volume
    #/${HOME}/storage For Linux filesystem
    #upload-dir: C:\\storage # For Windows filesystem
  jwt:
    secretKey: SuperSecretKey
    validityInMilliseconds: 3600000 #60*60000 = 1Hour