spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/psycontroldb
    username:
    password:
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: none
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

config:
  file:
    upload-dir: ${HOME}/Storage
  jwt:
    secretKey: SuperSecreto

logging:
  level:
    org:
      hibernate:
        #type:
        #descriptor:
        #sql:
        #BasicBinder: TRACE
        SQL: DEBUG
      springframework:
        security: DEBUG
