spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/psycontroldb
    username:
    password:
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: none
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

config:
  file:
    #upload-dir: ${HOME}/Storage # For Linux filesystem
    upload-dir: C:\\Storage # For Windows filesystem
  jwt:
    secretKey: SuperSecretKey
    validityInMilliseconds: 3600000 #60*60000 = 1Hour

logging:
  level:
    org:
      hibernate:
        #type:
        #descriptor:
        #sql:
        #BasicBinder: TRACE
        SQL: DEBUG
      springframework:
        security: DEBUG
